// CLAVE: CONEXIÓN ENTRE EL GENERADOR DE DOCUMENTOS Y SU CONTROLADOR (ROUTER DE DOCUMENTOS)
// ESTE ARCHIVO UNE EL FRONTEND Y EL BACKEND PARA MANEJAR TODO LO RELACIONADO CON DOCUMENTOS CREADOS POR EL USUARIO
// AQUÍ SE DEFINE QUÉ FUNCIÓN SE ACTIVA CUANDO UN USUARIO CREA, VE, DESCARGA O ELIMINA SUS DOCUMENTOS
// SE CONECTA DIRECTAMENTE CON EL ARCHIVO documentController.js Y CON authMiddleware.js PARA SEGURIDAD
// ESTE ARCHIVO LO ACTIVA EXPRESS CUANDO EL SERVIDOR RECIBE UNA PETICIÓN A /api/documents/... DESDE EL FRONTEND

// IMPORTA EXPRESS PARA PODER CREAR EL SISTEMA DE RUTAS
const express = require('express');
const router = express.Router();

// IMPORTA LAS FUNCIONES PRINCIPALES DESDE EL CONTROLADOR documentController.js
// ESTAS FUNCIONES MANEJAN TODA LA LÓGICA DE LOS DOCUMENTOS (CREAR, VER, BORRAR, OBTENER PLANTILLAS)
const { 
    generateDocument, 
    getTemplates, 
    getUserDocuments, 
    getDocument, 
    deleteDocument 
} = require('../controllers/documentController');

// IMPORTA EL MIDDLEWARE DE SEGURIDAD QUE VERIFICA SI EL USUARIO ESTÁ AUTENTICADO
// ESTE VIENE DE authMiddleware.js Y PROTEGE TODAS LAS RUTAS PARA QUE SOLO USUARIOS CON TOKEN PUEDAN USARLAS
const { protect } = require('../middleware/authMiddleware');

// RUTA PARA GENERAR UN NUEVO DOCUMENTO (SOLO USUARIOS AUTENTICADOS)
// SE UNE CON LA FUNCIÓN generateDocument DEL ARCHIVO documentController.js PARA CREAR Y GUARDAR EL DOCUMENTO
// ESTA RUTA LA ACTIVA EXPRESS CUANDO SE HACE UNA PETICIÓN POST A /api/documents/generate DESDE EL FRONTEND
router.post('/generate', protect, generateDocument);

// RUTA PARA OBTENER LAS PLANTILLAS DISPONIBLES PARA CREAR DOCUMENTOS
// SE UNE CON getTemplates DEL documentController.js Y DEVUELVE LAS OPCIONES DE TIPOS DE DOCUMENTO
// LA ACTIVA EXPRESS CUANDO EL USUARIO ENTRA A LA SECCIÓN DE PLANTILLAS EN EL FRONTEND
router.get('/templates', protect, getTemplates);

// RUTA PARA OBTENER TODOS LOS DOCUMENTOS CREADOS POR EL USUARIO
// SE UNE CON getUserDocuments DEL documentController.js Y MUESTRA SOLO LOS DOCUMENTOS DEL USUARIO ACTUAL
// LA ACTIVA EXPRESS CUANDO SE SOLICITA /api/documents/my-documents DESDE EL FRONTEND
router.get('/my-documents', protect, getUserDocuments);

// RUTA PARA OBTENER UN DOCUMENTO ESPECÍFICO POR SU ID
// SE UNE CON getDocument DEL documentController.js PARA MOSTRAR EL CONTENIDO COMPLETO DE ESE DOCUMENTO
// LA ACTIVA EXPRESS CUANDO EL FRONTEND PIDE UN DOCUMENTO EN /api/documents/:id
router.get('/:id', protect, getDocument);

// RUTA PARA ELIMINAR UN DOCUMENTO POR SU ID
// SE UNE CON deleteDocument DEL documentController.js Y BORRA EL DOCUMENTO DE LA BASE DE DATOS
// LA ACTIVA EXPRESS CUANDO EL FRONTEND ENVÍA UNA PETICIÓN DELETE A /api/documents/:id
router.delete('/:id', protect, deleteDocument);

// EXPORTA EL ROUTER PARA QUE PUEDA SER USADO EN EL ARCHIVO PRINCIPAL (server.js O app.js)
// SE UNE CON EXPRESS EN LA LÍNEA app.use('/api/documents', documentRoutes) DENTRO DEL SERVIDOR
// ESTE ARCHIVO SE PUEDE MODIFICAR PARA AÑADIR NUEVAS FUNCIONES, COMO EDITAR O COMPARTIR DOCUMENTOS ENTRE USUARIOS
module.exports = router;
